-- accounts schema

-- !Ups

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT DEFAULT '' NOT NULL,
    domain TEXT,
    display_name TEXT DEFAULT '' NOT NULL,
    locked BOOLEAN DEFAULT FALSE NOT NULL,
    bot BOOLEAN DEFAULT FALSE NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    url TEXT,
    fields JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (username, domain)
);

CREATE INDEX idx_accounts_username ON accounts (username);

CREATE INDEX idx_accounts_domain ON accounts (domain);

CREATE INDEX idx_accounts_created_at ON accounts (created_at);

CREATE INDEX idx_accounts_updated_at ON accounts (updated_at);

-- !Downs

DROP TABLE accounts;