-- users schema

-- !Ups

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    encrypted_password TEXT DEFAULT '' NOT NULL,
    sign_in_count INTEGER DEFAULT 0 NOT NULL,
    last_sign_in_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    locale TEXT,
    last_emailed_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    account_id BIGINT NOT NULL UNIQUE,
    disabled BOOLEAN DEFAULT FALSE NOT NULL,
    sign_up_ip INET,
    time_zone TEXT,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE INDEX idx_users_created_at ON users (created_at);

CREATE INDEX idx_users_updated_at ON users (updated_at);

CREATE INDEX idx_users_account_id ON users (account_id);

CREATE INDEX idx_users_last_sign_in_at ON users (last_sign_in_at);

CREATE INDEX idx_users_last_emailed_at ON users (last_emailed_at);

-- !Downs

DROP TABLE users;