-- statuses schema

-- !Ups

CREATE TABLE statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uri TEXT,
    text TEXT DEFAULT '' NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    in_reply_to_id BIGINT,
    reblog_of_id BIGINT,
    url TEXT,
    sensitive BOOLEAN DEFAULT FALSE NOT NULL,
    visibility INTEGER DEFAULT 0 NOT NULL,
    spoiler_text TEXT DEFAULT '' NOT NULL,
    reply BOOLEAN DEFAULT FALSE NOT NULL,
    language TEXT,
    conversation_id BIGINT,
    local BOOLEAN DEFAULT FALSE NOT NULL,
    account_id BIGINT NOT NULL,
    in_reply_to_account_id BIGINT,
    poll_id BIGINT,
    deleted_at TIMESTAMPTZ,
    edited_at TIMESTAMPTZ,
    media_attachment_ids BIGINT[] DEFAULT '{}' NOT NULL
);

CREATE INDEX idx_statuses_created_at ON statuses (created_at);

CREATE INDEX idx_statuses_updated_at ON statuses (updated_at);

CREATE INDEX idx_statuses_in_reply_to_id ON statuses (in_reply_to_id);

CREATE INDEX idx_statuses_reblog_of_id ON statuses (reblog_of_id);

CREATE INDEX idx_statuses_conversation_id ON statuses (conversation_id);

CREATE INDEX idx_statuses_account_id ON statuses (account_id);

CREATE INDEX idx_statuses_in_reply_to_account_id ON statuses (in_reply_to_account_id);

CREATE INDEX idx_statuses_poll_id ON statuses (poll_id);

CREATE INDEX idx_statuses_deleted_at ON statuses (deleted_at);

CREATE INDEX idx_statuses_edited_at ON statuses (edited_at);

-- !Downs

DROP TABLE statuses;