-- follow_requests schema

-- !Ups

CREATE TABLE follow_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    account_id BIGINT NOT NULL,
    target_account_id BIGINT NOT NULL,
    show_reblogs BOOLEAN DEFAULT TRUE NOT NULL,
    uri TEXT,
    inform BOOLEAN DEFAULT FALSE NOT NULL,
    languages TEXT[]
);

CREATE UNIQUE INDEX idx_follow_requests_account_id_and_target_account_id
    ON follow_requests (account_id, target_account_id);

-- !Downs

DROP TABLE follow_requests;

-- follows schema

-- !Ups

CREATE TABLE follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    account_id BIGINT NOT NULL,
    target_account_id BIGINT NOT NULL,
    show_reblogs BOOLEAN DEFAULT TRUE NOT NULL,
    uri TEXT,
    inform BOOLEAN DEFAULT FALSE NOT NULL,
    languages TEXT[]
);

CREATE UNIQUE INDEX idx_follows_account_id_and_target_account_id
    ON follows (account_id, target_account_id);

CREATE INDEX idx_follows_target_accountId
    ON follows (target_account_id);

-- !Downs

DROP TABLE follows;
