-- media schema

-- !Ups

CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    content_type TEXT,
    file_size BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    account_id BIGINT NOT NULL,
    blurhash TEXT NOT NULL,
    processing BOOLEAN NOT NULL DEFAULT FALSE,
    thumbnail_file_name TEXT NOT NULL,
    thumbnail_content_type TEXT,
    thumbnail_file_size BIGINT NOT NULL,
    url TEXT,
    thumbnail_url TEXT,
    remote_url TEXT,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE INDEX idx_media_account_id
    ON media (account_id);

-- !Downs

DROP TABLE media;
